const Map<String, String> appTextEn = <String, String>{
  'noorify': 'Noorify demo logo',
  'splashTitle': 'Find Peace Through Faith',
  'splashQuote':
      'Build meaningful daily habits with Quran recitation, duas, and timely prayer reminders.',
  'emailOrPhoneHint': 'Email Or Phone No',
  'passwordHint': 'Password',
  'forgotPassword': 'Forgot Password',
  'login': 'Login',
  'newToNoorify': 'New To Noorify?',
  'createAccount': 'Create Account',
  'signUpSubtitle':
      'Begin your journey toward a more mindful Islamic lifestyle.',
  'enterYourName': 'Enter Your Name',
  'emailAddress': 'Email Address',
  'emailVerification': 'Email Verification',
  'sendOtp': 'Send OTP',
  'otpVerification': 'OTP Verification',
  'verify': 'Verify',
  'resendIn': 'Resend In  01: 23 S',
  'resetPassword': 'Reset Password',
  'newPassword': 'New Password',
  'confirm': 'Confirm',
  'phoneNo': 'Phone No',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'confirmPassword': 'Confirm Password',
  'signUpWithOthers': 'SignUp with Others',
  'togglePassword': 'Toggle password',
  'iAgreeToThe': 'I Agree To The',
  'termsOfServices': 'Terms Of Services',
  'privacyPolicy': 'Privacy Policy',
  'alreadyHaveAccount': 'Already Have An Account?',
  'logIn': 'Log In',

  // Shared
  'back': 'Back',

  // Alarm feature
  'setAlarm': 'Set Alarm',
  'setAllAlarm': 'Set All Alarm',
  'vibrateAndRing': 'Vibrate and ring',
  'setRingtone': 'Set Ringtone',
  'vibrate': 'Vibrate',
  'ring': 'Ring',
  'searchHere': 'Search Here . . .',
  'setAlarmBeforePrayer': 'Set Alarm Before Prayer',
  'setAlarmFor': 'Set alarm for',
  'offsetAtPrayerTime': 'At prayer time',
  'offsetBefore5Min': 'Before 5 Min',
  'offsetBefore10Min': 'Before 10 Min',
  'offsetBefore15Min': 'Before 15 Min',
  'offsetBefore20Min': 'Before 20 Min',
  'offsetBefore30Min': 'Before 30 Min',
  'offsetBefore40Min': 'Before 40 Min',
  'offsetBefore60Min': 'Before 60 Min',

  // Amol tracking feature
  'amolTracking': 'Amol Tracking',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'point': 'Point',
  'myPoints': 'My points',
  'todaysAmolTrack': 'Todays Amol track',
  'amolTrack': 'Amol Track',
  'todays': 'Todays',
  'averageTodaysDays': '–  average todays days.',
  'myPosition': 'My Position',
  'myNearestOrCompetitor': 'My Nearest Or Competitor',
  'competitorInitials': 'Ab',
  'viewInDashboard': 'View in dashboard',
  'categoryFardhPrayer': 'Fardh Prayer',
  'categorySunnahAndWitr': 'Sunnah and Witr',
  'categoryQuran': 'Quran',
  'categoryNaflSalat': 'Nafl Salat',
  'categoryHadith': 'Hadith',
  'categoryQuiz': 'Quiz',
  'categoryNaflAndMore': 'Nafl & more',
  'salahFajr': 'Fajr',
  'salahDuhr': 'Duhr',
  'salahAsr': 'Asr',
  'salahMagrib': 'Magrib',
  'salahEsa': 'Esa',
  'salahFajrSunnah': 'Fajr Sunnah',
  'salahDuhrSunnah': 'Duhr Sunnah',
  'salahAsrSunnah': 'Asr Sunnah',
  'salahMagribSunnah': 'Magrib Sunnah',
  'salahEsaSunnah': 'Esa Sunnah',
  'salahWitr': 'Witr',
  'naflTahajjud': 'Tahajjud',
  'naflIshraq': 'Ishraq',
  'naflChast': 'Chast',
  'naflAwabin': 'Awabin',
  'moreSadaqah': 'Sadaqah',
  'moreKarzeHasanah': 'Karze Hasanah',
  'moreNaflFasting': 'Nafl Fasting',
  'morePhysicalExercise': 'Physical Exercise',
  'moreGivenGoodAdvice': 'Given Good Ad Vice',
  'moreSkillDevelopment': 'Skill Development',
  'infoQuranTilawat': 'Quran Tilawat',
  'infoHadithReading': 'Hadith Reading',
  'infoGivingQuiz': 'Giving Quiz',
  'weekdayMonday': 'Monday',
  'weekdayTuesday': 'Tuesday',
  'weekdayWednesday': 'Wednesday',
  'weekdayThursday': 'Thursday',
  'weekdayFriday': 'Friday',
  'weekdaySaturday': 'Saturday',
  'weekdaySunday': 'Sunday',
  'monthJanuary': 'January',
  'monthFebruary': 'February',
  'monthMarch': 'March',
  'monthApril': 'April',
  'monthMay': 'May',
  'monthJune': 'June',
  'monthJuly': 'July',
  'monthAugust': 'August',
  'monthSeptember': 'September',
  'monthOctober': 'October',
  'monthNovember': 'November',
  'monthDecember': 'December',

  // Shared social labels
  'google': 'Google',
  'facebook': 'Facebook',

  // Auth error messages
  'authErrorInvalidEmail': 'Please enter a valid email address.',
  'authErrorUserDisabled': 'This account has been disabled.',
  'authErrorWrongCredentials': 'Email or password is incorrect.',
  'authErrorAccountNotPasswordBased':
      'This account uses Google sign-in. Password change is unavailable.',
  'authErrorEmailInUse': 'This email is already in use. Please sign in.',
  'authErrorWeakPassword': 'Password is too weak. Use at least 6 characters.',
  'authErrorOperationNotAllowed':
      'This sign-in method is not enabled in Firebase.',
  'authErrorRequiresRecentLogin':
      'Please sign in again before changing password.',
  'authErrorAccountExistsDifferentCredential':
      'An account already exists with a different sign-in method.',
  'authErrorCredentialAlreadyInUse':
      'This Google account is already linked with another user.',
  'authErrorTooManyRequests': 'Too many attempts. Try again later.',
  'authErrorNetworkFailed':
      'Network error. Please check your internet connection.',
  'authErrorGeneric': 'Authentication failed. Please try again.',
  'googleAuthErrorNotConfigured':
      'Google sign-in is not configured correctly yet.',
  'googleAuthErrorUiUnavailable':
      'Google sign-in is currently unavailable on this device.',
  'googleAuthErrorInterrupted':
      'Google sign-in was interrupted. Please try again.',
  'googleAuthErrorGeneric': 'Google sign-in failed. Please try again.',

  // Dashboard feature
  'dashboard': 'Dashboard',
  'quizHistory': 'Quiz history',
  'seeAll': 'See All',
  'averageValue': 'average value',
  'dailyQuizValue': 'Daily Quiz Value',
  'weeklyQuizValue': 'Weekly Quiz Value',
  'monthlyQuizValue': 'Monthly Quiz Value',
  'competitorName': 'Abdullah Al-Aziz',
  'quranicScience': 'Quranic Science',
  'questionsCountLabel': '20 Questions',

  // Home feature
  'greeting': 'Assalamu Alaikum Wa Rahmatullah',
  'timer': 'Timer',
  'notifications': 'Notifications',
  'featureDua': 'Dua',
  'featureDijpr': 'Dijpr',
  'featureAsmaUlHusna': 'Asma-ul Husna',
  'featureQuizAndLearn': 'Quiz & Learn',
  'zakatCalculator': 'Zakat Calculator',
  'ageCalculate': 'Age Calculate',
  'home': 'Home',
  'todaysHighestValue': 'Todays highest value',
  'todays2ndHighest': 'Todays 2nd highest',
  'yesterdaysHighest': 'Yesterdays highest',
  'khalidSaifullah': 'Khalid Saifullah',
  'myPositionInMonth': 'My position in, July',
  'firstInTheMonth': '1st In The Month',
  'secondInTheMonth': '2nd In The Month',
  'lastMonthWinner': 'Last Month Winner',
  'sehri': 'Sehri',
  'iftar': 'Iftar',
  'hijriDatePlaceholder': '7 Safar 1444 Hijri',
  'bengaliDatePlaceholder': '7 Srabon 1433',
  'gregorianDatePlaceholder': '24 July 2026',
  'locationPlaceholder': 'Mymensingh, Bangladesh',
  'viewPrayerTimes': 'View prayer times',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset',
  'trishal': 'Trishal',
  'sunriseTimePlaceholder': 'at 5:23 AM',
  'sunsetTimePlaceholder': 'at 6:54 PM',
  'dhuhrPrayerTime': 'Dhuhr Prayer Time',
  'prohibitedPrayerTimes': 'Prohibited Prayer Times',
  'jawaal': 'Jawaal',
  'prayerTimesTitle': 'Prayer times',
  'hijriDateUnavailable': 'Hijri date unavailable',
  'nextPrefix': 'Next:',
  'prayerTimeSuffix': 'Prayer Time',
  'prayerFajr': 'Fajr',
  'prayerDhuhr': 'Dhuhr',
  'prayerAsr': 'Asr',
  'prayerMaghribAndIftar': 'Maghrib & Iftar',
  'prayerIsha': 'Isha',

  // Learning feature
  'learning': 'Learning',
  'explore': 'Explore',
  'exploreQuranicSciences': 'Quranic Sciences',
  'exploreDailyLife': 'Daily life',
  'exploreIslamicHistory': 'Islamic history',
  'articlesCountLabel': 'Articles',
  'recentArticles': 'Recent articles',
  'articleTitleSabr': 'The Power of Sabr in Islam',
  'articleTagIslamicGuidance': 'Islamic Guidance',
  'articleExcerptSabr':
      'Learn how patience helps Muslims remain steadfast\nthrough difficulties and strengthens their trust in Allah.',
  'seeMore': 'See More . . .',
  'postDatePlaceholder': 'Post Date: August 17, 2026   10:00 AM',
  'allArticles': 'All articles',
  'articlesDetails': 'Articles Details',
  'testLearning': 'Test learning',
  'articleFullTextSabr':
      '''Sabr, or patience, is one of the most important virtues in Islam. It teaches believers to remain steadfast during hardships, control their emotions, and continue trusting in Allah's wisdom and plan. Life brings challenges, tests, and moments of uncertainty, but Sabr helps Muslims face these difficulties with faith, hope, and perseverance.

Patience does not mean giving up or simply waiting for problems to disappear. It means continuing to do what is right, maintaining faith during difficult moments, and seeking Allah's guidance when facing challenges. Through Sabr, a believer learns to respond to hardship with strength rather than despair.

The Quran reminds believers that Allah is with those who are patient. This gives Muslims comfort during difficult times and encourages them to remain hopeful.''',
  'questionProgressLabel': 'Question 12 of 20',
  'questionsTitlePlaceholder': 'Questions title',
  'answerLabelPrefix': 'Answer',
  'quizTimingProgress': 'This quiz timing progress',
  'previous': 'Previous',
  'next': 'Next',
  'timesRemainingLabel': 'Times remaining : 07 : 03 sec',
  'quizScore': 'Quiz score',
  'testSubjectSabr': 'Sabr',
  'excellentWorkMessage':
      'Excellent Work! Your Answering Accuracy Is Very Good.\nKeep Up The Great Effort, And Continue Challenging\nYourself To Improve Even Further.',
  'timeSpent': 'Time Spent',
  'accuracy': 'Accuracy',
  'accuracyHigh': 'High',
  'whatsNext': 'Whats Next',
  'whatsNextMessage':
      'Would you like to move on to the next quiz? Click Next to\ncontinue, or choose Retry to retake the quiz and\nstrengthen your understanding.',
  'continueToNext': 'Continue To Next',
  'retryQuiz': 'Retry Quiz',
  'overallScore': 'Overall score',
  'correctAnswers': 'Correct answers',
  'incorrectAnswers': 'Incorrect answers',
  'correctAnswersMessage':
      'You are trying your best your correct answer is 13 out of 20. Lets try to read learn more.',
  'incorrectAnswersMessage':
      'You are trying your best your correct answer is 7 out of 20. View incorrect answer and learn about it.',
  'viewCorrectAnswer': 'View Correct Answer',
  'viewIncorrectAnswer': 'View Incorrect Answer',

  // Planner feature
  'plannerPlanOne': 'Plan 1',
  'plannerPlanTwo': 'Plan 2',
  'createPlan': 'Create Plan',
  'myPlan': 'My Plan',
  'completePlan': 'Complete Plan',
  'noCompletedPlansMessage': 'You cannot complete any\nplan yet !',
  'getStart': 'Get Start',
  'createPlanHeader': 'Create plan',
  'planNameLabel': 'Plan name',
  'writeHereHint': 'Write Here . . .',
  'selectQuizCategory': 'Select quiz category',
  'egQuranicScienceHint': 'Eg : Quranic science',
  'selectQuiz': 'Select quiz',
  'egQuiz1Hint': 'Eg : Quiz 1',
  'add': 'Add',
  'create': 'Create',
  'addMore': 'Add More',

  // Quiz feature
  'categories': 'Categories',
  'quizzesCountLabel': 'Quizzes',
  'seerahAndHistory': 'Seerah & History',
  'islamicManners': 'Islamic Manners',
  'completeTodaysChallenge': 'Complete your todays\nchallenge',
  'letsGetStart': 'Lets Get Start',
  'highScore': 'High Score',
  'quizQuestionProgressLabel': 'Question 8 of 12',
  'fiftyFiftyChance': '50/50  CHANCE',
  'youCompletedTodaysChallenge': 'You completed your\ntodays challenge',
  'todaysPointsLabel': 'Todays points',
  'completedHistory': 'Completed History',
  'unableToLoadQuizHistory': 'Unable to load quiz history.',
  'tryAgain': 'Try again',
  'questionsWord': 'Questions',
  'learn': 'Learn',
  'planner': 'Planner',

  // Profile feature
  'profileTitle': 'Profile',
  'percentCompleteSuffix': 'complete',
  'mymensingh': 'Mymensingh',
  'badgeLabel': 'Badge',
  'position': 'Position',
  'pointsWord': 'Points',
  'familyMember': 'Family Member',
  'brother': 'Brother',
  'familyMemberNameAbdullah': 'Abdullah',
  'familyMemberNameSabit': 'Sabit',
  'familyMemberNameAli': 'Ali',
  'logout': 'Logout',

  // Settings feature
  'settingsTitle': 'Settings',
  'aboutUs': 'About us',
  'ourProducts': 'Our products',
  'adminSupport': 'Admin support',
  'feedback': 'Feedback',
  'appLanguage': 'App language',
  'changePassword': 'Change password',
  'deleteAccount': 'Delete account',

  // App language feature
  'languageTitle': 'Language',
  'bangla': 'Bangla',
  'english': 'English',
  'defaultLabel': 'Default',
  'allFamilyMembers': 'All Family Members',
  'familyMemberNameZulfikur': 'Zulfikur',
  'familyMemberNameAsif': 'Asif',

  // Quran feature
  'searchSurah': 'Search surah',
  'surahsTitle': 'Surahs',
  'ayahWord': 'Ayahs',
  'surahMeaningOpening': 'The Opening',
  'surahMeaningCow': 'The Cow',
  'surahMeaningFamilyOfImran': 'The Family of Imran',
  'surahMeaningWomen': 'The Women',
  'quranIntroSubtitle': 'Learn Quran and Recite once everyday',
  'quranLoadError': "Couldn't load the Quran. Please check your connection.",
  'hifjoQuranTitle': 'Hifjo Quran',
  'lastReadLabel': 'Last Read',
  'viewReadingHistory': 'View reading history',
  'ayahNoLabel': 'Ayah No',
  'tabSurah': 'Surah',
  'tabPara': 'Para',
  'meccan': 'Meccan',
  'medinian': 'Medinian',
  'juzWord': 'Juz',
  'startsLabel': 'Starts',
  'bookmarksTitle': 'Bookmarks',
  'noBookmarksYet': 'No bookmarks yet',
  'readingHistoryTitle': 'Reading History',
  'noReadingHistoryYet': 'No reading history yet',
  'startReadingPrompt': 'Tap a surah below to begin',
  'viewFullSura': 'View Full Sura',
  'pointsLabel': 'Points',
  'yourReadingTimeIs': 'Your reading time is',
  'minLabel': 'min',
  'secLabel': 'sec',
  'viewQuranTafsir': 'View Quran Tafsir',
  'selectReciterTitle': 'Select Reciter',
  'tafsirTitle': 'Tafsir',
};
