const Map<String, String> appTextEn = <String, String>{
  'tuhfatulMuslim': 'Tuhfatul Muslim',
  'splashTitle': 'Find Peace Through Faith',
  'splashQuote':
      'Build meaningful daily habits with Quran recitation, duas, and timely prayer reminders.',
  'emailOrPhoneHint': 'Email Or Phone No',
  'passwordHint': 'Password',
  'forgotPassword': 'Forgot Password',
  'login': 'Login',
  'newToTuhfatulMuslim': 'New To Tuhfatul Muslim?',
  'createAccount': 'Create Account',
  'guestUser': 'Continue as Guest',
  'signUpSubtitle':
      'Begin your journey toward a more mindful Islamic lifestyle.',
  'enterYourName': 'Enter Your Name',
  'emailAddress': 'Email Address',
  'emailCopied': 'Email copied to clipboard',
  'emailVerification': 'Email Verification',
  'sendOtp': 'Send OTP',
  'otpVerification': 'OTP Verification',
  'verify': 'Verify',
  'resendIn': 'Resend In  01: 23 S',
  'resetPassword': 'Reset Password',
  'newPassword': 'New Password',
  'confirm': 'Confirm',
  'phoneNo': 'Phone No',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'confirmPassword': 'Confirm Password',
  'signUpWithOthers': 'SignUp with Others',
  'togglePassword': 'Toggle Password',
  'iAgreeToThe': 'I Agree To The',
  'termsOfServices': 'Terms Of Services',
  'privacyPolicy': 'Privacy Policy',
  'alreadyHaveAccount': 'Already Have An Account?',
  'logIn': 'Log In',

  // Shared
  'back': 'Back',
  'comingSoon': 'Coming Soon',

  // Alarm feature
  'alarm': 'Alarm',
  'setAlarm': 'Set Alarm',
  'setAllAlarm': 'Set All Alarm',
  'allAlarm': 'All Alarm',
  'prayersAlarm': 'Prayers Alarm',
  'alarmWillRingIn': 'Alarm will be ring in',
  'hrLabel': 'hr',
  'noAlarmSet': 'No alarm set',
  'alarmLabel': 'Label',
  'alarmLabelHint': 'e.g. Wake up',
  'vibrateAndRing': 'Vibrate And Ring',
  'setRingtone': 'Set Ringtone',
  'vibrate': 'Vibrate',
  'ring': 'Ring',
  'searchHere': 'Search Here . . .',
  'setAlarmBeforePrayer': 'Set Alarm Before Prayer',
  'setAlarmFor': 'Set Alarm For',
  'offsetAtPrayerTime': 'At Prayer Time',
  'offsetBefore5Min': 'Before 5 Min',
  'offsetBefore10Min': 'Before 10 Min',
  'offsetBefore15Min': 'Before 15 Min',
  'offsetBefore20Min': 'Before 20 Min',
  'offsetBefore30Min': 'Before 30 Min',
  'offsetBefore40Min': 'Before 40 Min',
  'offsetBefore60Min': 'Before 60 Min',
  'offsetCustom': 'Custom',
  'offsetMinutesUnit': 'Minutes',
  'alarmCancel': 'Cancel',
  'alarmSet': 'Set',
  'allAlarmsSaved': 'Prayer alarms saved',
  'alarmIsRinging': 'Alarm',
  'stopAlarm': 'Stop',
  'snoozeAlarm': 'Snooze 5 min',
  'deleteAlarmTitle': 'Delete Alarm',
  'deleteAlarmMessage': 'Are you sure you want to delete this alarm?',
  'deleteAlarmConfirm': 'Delete',
  'deleteRingtoneTitle': 'Delete Ringtone',
  'deleteRingtoneMessage': 'Are you sure you want to delete this ringtone?',
  'deleteRingtoneConfirm': 'Delete',
  'alarmNotSetForPrayer': 'Alarm not set for this prayer',
  'exactAlarmPermissionNeeded':
      'Please allow alarms & reminders in Settings so your prayer alarms '
      'can ring on time.',

  // Amol tracking feature
  'amolTracking': 'Amol Tracking',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'point': 'Point',
  'myPoints': 'My Points',
  'todaysAmolTrack': 'Todays Amol Track',
  'amolTrack': 'Amol Track',
  'todays': 'Todays',
  'averageTodaysDays': '–  average todays days.',
  'myPosition': 'My Position',
  'myNearestOrCompetitor': 'My Nearest Or Competitor',
  'competitorInitials': 'Ab',
  'viewInDashboard': 'View In Dashboard',
  'amolPrayerTimeNotStarted': 'The time for {name} has not started yet.',
  'ok': 'OK',
  'categoryFardhPrayer': 'Fardh Prayer',
  'categorySunnahAndWitr': 'Sunnah And Witr',
  'categoryQuran': 'Quran',
  'categoryNaflSalat': 'Nafl Salat',
  'categoryZikr': 'Zikr',
  'categoryHadith': 'Hadith',
  'hadithIntroTitle': 'Hadith and books',
  'hadithIntroSubtitle':
      'Access verified hadith from trusted Islamic sources to support daily learning, reflection, and spiritual growth.',
  'hadithIntroStartButton': "Let's Get Start",
  'hadithTotalHadith': 'Total Hadith',
  'hadithLastRead': 'Last read',
  'hadithLibrary': 'Hadith library',
  'hadithEbook': 'E-book',
  'hadithLibraryTitle': 'Hadith Library',
  'hadithCategory': 'Hadith Category',
  'hadithSubCategory': 'Hadith Sub Category',
  'hadithBookDownloadTitle': 'Download to read offline',
  'hadithBookDownloadBody':
      'This book is saved to your device once, then opens instantly and works without internet.',
  'hadithBookDownloadAction': 'Download Book',
  'hadithBookDownloading': 'Downloading book',
  'hadithBookComingSoon': 'Coming soon',
  'hadithBookReference': 'Reference',
  'hadithSwipeNext': 'Swipe for the next hadith',
  'hadithCopy': 'Copy hadith',
  'hadithCopied': 'Hadith copied',
  'hadithShare': 'Share',
  'hadithCopyTranslation': 'Copy translation',
  'hadithCopyArabic': 'Copy Arabic',
  'hadithCopyFull': 'Copy full hadith',
  'hadithShareScreenshot': 'Share as screenshot',
  'hadithReport': 'Report',
  'hadithShareFailed': 'Could not create the screenshot',
  'hadithReportFailed': 'No email app found on this device',
  'hadithReportMessage':
      'I would like to report an issue with the hadith below. Please describe the problem:\n\n',
  'hadithBookmark': 'Bookmark',
  'hadithBookmarkAdded': 'Saved to bookmarks',
  'hadithBookmarkRemoved': 'Removed from bookmarks',
  'bookmarkSheetTitle': 'Book Mark',
  'searchFolderHint': 'Search Folder . . .',
  'createFolderAction': 'Create folder',
  'saveAction': 'Save',
  'favoriteFolder': 'Favorite',
  'folderNameHint': 'Folder name',
  'hadithBookRef': 'Book reference',
  'hadithRefAuthor': 'Author',
  'hadithRefTranslator': 'Translator',
  'hadithRefEditors': 'Editors',
  'hadithRefPublisher': 'Publisher',
  'hadithRefYear': 'Year',
  'savedHadithTitle': 'Saved Hadith',
  'saved': 'Saved',
  'noSavedHadithMessage': 'You haven’t saved any\nhadith yet !',
  'noResultsFound': 'No results found',
  'savedTabHadith': 'Hadith',
  'savedTabFolder': 'Folder',
  'noFoldersMessage': 'No folders yet !',
  'totalReadingHadith': 'Total Reading hadith',
  'totalReadingTime': 'Total Reading time',
  'ebookLabel': 'E-Book',
  'noReadingHistory': 'No reading history yet',
  'hadithNoLabel': 'Hadith No',
  'totalSavedLabel': 'Total Saved',
  'newFolder': 'New folder',
  'categoryQuiz': 'Quiz',
  'categoryNaflAndMore': 'Nafl & More',
  'compassTitle': 'Compass',
  'kiblahLabel': 'Kiblah',
  'viewFullScreen': 'View Full Screen',
  'compassDirectionEast': 'East',
  'compassDirectionWest': 'West',
  'compassLocationServicesDisabled':
      'Turn on location services to find the Qiblah direction.',
  'compassPermissionDenied':
      'Tuhfatul Muslim needs location access to point the compass toward the Kaaba.',
  'compassUnsupported': "This device doesn't have a compass sensor.",
  'compassOpenSettings': 'Open Settings',
  'compassEnableLocation': 'Enable Location',
  'compassCalibrationHint': 'Move your phone in a figure-8 to improve accuracy',
  'kiblahCompassTitle': 'Kiblah Compass',
  'compassDirectionLeft': 'Left',
  'compassDirectionRight': 'Right',
  'salahFajr': 'Fajr',
  'salahDuhr': 'Duhr',
  'salahAsr': 'Asr',
  'salahMagrib': 'Magrib',
  'salahEsa': 'Esa',
  'salahFajrSunnah': 'Fajr Sunnah',
  'salahDuhrSunnah': 'Duhr Sunnah',
  'salahAsrSunnah': 'Asr Sunnah',
  'salahMagribSunnah': 'Magrib Sunnah',
  'salahEsaSunnah': 'Esa Sunnah',
  'salahWitr': 'Witr',
  'naflTahajjud': 'Tahajjud',
  'naflIshraq': 'Ishraq',
  'naflChast': 'Chast',
  'naflAwabin': 'Awabin',
  'moreSadaqah': 'Sadaqah/Hadiya',
  'moreKarzeHasanah': 'Karze Hasanah',
  'moreRozaKaffarah': 'Roza/Kaffarah',
  'moreNaflFasting': 'Nafl Fasting',
  'morePhysicalExercise': 'Physical Exercise',
  'moreGivenGoodAdvice': 'Given Good Ad Vice',
  'moreSkillDevelopment': 'Skill Development',
  'infoQuranTilawat': 'Quran Tilawat',
  'infoHadithReading': 'Hadith Reading',
  'infoGivingQuiz': 'Giving Quiz',
  'weekdayMonday': 'Monday',
  'weekdayTuesday': 'Tuesday',
  'weekdayWednesday': 'Wednesday',
  'weekdayThursday': 'Thursday',
  'weekdayFriday': 'Friday',
  'weekdaySaturday': 'Saturday',
  'weekdaySunday': 'Sunday',
  'monthJanuary': 'January',
  'monthFebruary': 'February',
  'monthMarch': 'March',
  'monthApril': 'April',
  'monthMay': 'May',
  'monthJune': 'June',
  'monthJuly': 'July',
  'monthAugust': 'August',
  'monthSeptember': 'September',
  'monthOctober': 'October',
  'monthNovember': 'November',
  'monthDecember': 'December',

  // Shared social labels
  'google': 'Google',
  'facebook': 'Facebook',

  // Auth error messages
  'authErrorInvalidEmail': 'Please enter a valid email address.',
  'authErrorUserDisabled': 'This account has been disabled.',
  'authErrorWrongCredentials': 'Email or password is incorrect.',
  'authErrorAccountNotPasswordBased':
      'This account uses Google sign-in. Password change is unavailable.',
  'authErrorEmailInUse': 'This email is already in use. Please sign in.',
  'authErrorWeakPassword': 'Password is too weak. Use at least 6 characters.',
  'authErrorOperationNotAllowed':
      'This sign-in method is not enabled in Firebase.',
  'authErrorRequiresRecentLogin':
      'Please sign in again before changing password.',
  'authErrorAccountExistsDifferentCredential':
      'An account already exists with a different sign-in method.',
  'authErrorCredentialAlreadyInUse':
      'This Google account is already linked with another user.',
  'authErrorTooManyRequests': 'Too many attempts. Try again later.',
  'authErrorNetworkFailed':
      'Network error. Please check your internet connection.',
  'authErrorGeneric': 'Authentication failed. Please try again.',
  'googleAuthErrorNotConfigured':
      'Google sign-in is not configured correctly yet.',
  'googleAuthErrorUiUnavailable':
      'Google sign-in is currently unavailable on this device.',
  'googleAuthErrorInterrupted':
      'Google sign-in was interrupted. Please try again.',
  'googleAuthErrorGeneric': 'Google sign-in failed. Please try again.',

  // Dashboard feature
  'dashboard': 'Dashboard',
  'quizHistory': 'Quiz History',
  'seeAll': 'See All',
  'averageValue': 'Average Value',
  'dailyQuizValue': 'Daily Quiz Value',
  'weeklyQuizValue': 'Weekly Quiz Value',
  'monthlyQuizValue': 'Monthly Quiz Value',
  'competitorName': 'Abdullah Al-Aziz',
  'quranicScience': 'Quranic Science',
  'questionsCountLabel': '20 Questions',

  // Home feature
  'greeting': 'Assalamu Alaikum Wa Rahmatullah',
  'prayerReminderPrefix': 'Have you completed',
  'prayerReminderSuffix': 'prayer yet?',
  'timer': 'Timer',
  'notifications': 'Notifications',
  'noNotificationsAvailable': 'No notifications available',
  'notificationUnread': 'Unread',
  'notificationRead': 'Read',
  'featureDua': 'Dua',
  'featureDijpr': 'Zikr',
  'featureAsmaUlHusna': 'Asma-ul Husna',
  'asmaHusnaTitle': 'Asmaul-Husna',
  'asmaHusnaHadithNarrator':
      'Abu Huraira (May Allah Be Pleased With Him) Reported That The Messenger Of Allah ﷺ Said:',
  'asmaHusnaHadithArabic':
      'إِنَّ لِلَّهِ تِسْعَةً وَتِسْعِينَ اسْمًا مِائَةً إِلَّا وَاحِدَةً مَنْ أَحْصَاهَا دَخَلَ الْجَنَّةَ',
  'asmaHusnaHadithTranslation':
      '"Indeed, Allah has ninety-nine names, one hundred minus one. Whoever memorizes them (or enumerates/preserves them) will enter Paradise."',
  'asmaHusnaSourcesLabel': 'Sources:',
  'asmaHusnaSourceBukhari': 'Sahih Al-Bukhari (Hadith 2736 / 7392)',
  'asmaHusnaSourceMuslim': 'Sahih Muslim (Hadith 2677)',
  'asmaHusnaAgreedNote':
      'This Is A Muttafaqun Alayhi Hadith (Agreed Upon By Both Bukhari And Muslim).',
  'asmaHusnaNamesCount': '99 Name',
  'asmaHusnaClickDetails': 'Click to see details',
  'featureQuizAndLearn': 'Quiz & Learn',
  'zikrIntroTitle': 'Zikr',
  'zikrIntroSubtitle':
      'Stay connected to Allah through daily remembrance, guided supplications, and a peaceful spiritual routine.',
  'zikrIntroStartButton': "Let's Get Start",
  'zikrTitle': 'Zikr',
  'zikrTotalZikr': 'Total Zikr',
  'zikrLastZikr': 'Last Zikr',
  'zikrMyCreatedZikr': 'My Created Zikr',
  'zikrGetStart': 'Get start',
  'zikrAllTitle': 'All Zikr',
  'zikrCounterReset': 'Reset',
  'zikrCreateTitle': 'Create Zikr',
  'zikrCreateNameHint': 'Zikr name',
  'zikrCreateTargetHint': 'Target count',
  'zikrCreateAdd': 'Add',
  'zikrNewTitle': 'New Zikr',
  'zikrSelectZikr': 'Select Zikr',
  'zikrSetReadingValue': 'Set reading value',
  'zikrReadingValueHint': 'Eg : 33',
  'zikrCreate': 'Create',
  'zikrCreated': 'Zikr created',
  'zikrCustom': 'Custom',
  'zikrCancel': 'Cancel',
  'zikrWriteZikrName': 'Write Your Zikr Name',
  'zikrWriteZikrNameHint': 'Write Zikr Name',
  'zikrAddMore': 'Add More',
  'zikrPlanCreateTitle': 'Create plan',
  'zikrPlanName': 'Plan name',
  'zikrPlanCompletionDays': 'Completion days',
  'zikrPlanWriteHere': 'Write Here . . .',
  'zikrPlanComplete': 'Complete',
  'zikrPlanDays': 'Days',
  'zikrTodaysValueGraph': 'Todays Value In Graph',
  'zikrMostDoing': 'Most Doing Zikr',
  'zikrHistory': 'Zikr History',
  'zikrTapToCount': 'Tap to Count',
  'zikrCompletingProgress': 'Completing progress',
  'zikrCompleted': 'Completed',
  'zikrNameSubhanAllah': 'SubhanAllah',
  'zikrNameAlhamdulillah': 'Alhamdulillah',
  'zikrNameAllahuAkbar': 'Allahu Akbar',
  'zikrNameFinalZikr':
      "La ilaha illallahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadir",
  'duaIntroTitle': 'Dua',
  'duaIntroSubtitle': 'Strengthen your faith through daily supplication',
  'duaIntroStartButton': "Let's Get Start",
  'duaFeaturedTitle': 'Featured Dua',
  'duaCategoryTitle': 'Duas Category',
  'duaAllCategoryTitle': 'All Category',
  'duaTotalCategoryLabel': 'Total Category',
  'duaSearchCategoryHint': 'Search Category',
  'duaTotalFeaturedLabel': 'Total Featured Dua',
  'duaExplore': 'Explore',
  'duaTotalDuaLabel': 'Total Dua',
  'duaAllDuaTitle': 'All Dua',
  'duaLastRead': 'Last read',
  'duaRecitePrefix': 'Recite the following statement',
  'duaReciteSuffix': 'times -',
  'duaBookmarkAdded': 'Saved to bookmark',
  'duaCreateFolderTitle': 'Create Folder',
  'duaFolderNameFieldHint': 'Write Folder Name Here.',
  'duaCancel': 'Cancel',
  'zakatCalculator': 'Zakat Calculator',
  'ageCalculate': 'Age Calculate',
  'home': 'Home',
  'todaysHighestValue': 'Todays Highest Value',
  'todays2ndHighest': 'Todays 2nd Highest',
  'yesterdaysHighest': 'Yesterdays Highest',
  'khalidSaifullah': 'Khalid Saifullah',
  'myPositionInMonth': 'My Position In, July',
  'firstInTheMonth': '1st In The Month',
  'secondInTheMonth': '2nd In The Month',
  'lastMonthWinner': 'Last Month Winner',
  'sehri': 'Sehri',
  'iftar': 'Iftar',
  'hijriDatePlaceholder': '7 Safar 1444 Hijri',
  'bengaliDatePlaceholder': '7 Srabon 1433',
  'gregorianDatePlaceholder': '24 July 2026',
  'locationPlaceholder': 'Mymensingh, Bangladesh',
  'locationFinding': 'Finding your location…',
  'locationServiceDisabled': 'Turn on location services',
  'locationPermissionDenied': 'Location permission is needed',
  'locationUnavailable': 'Location unavailable',
  'viewPrayerTimes': 'View Prayer Times',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset',
  'trishal': 'Trishal',
  'sunriseTimePlaceholder': 'at 5:23 AM',
  'sunsetTimePlaceholder': 'at 6:54 PM',
  'dhuhrPrayerTime': 'Dhuhr Prayer Time',
  'prohibitedPrayerTimes': 'Prohibited Prayer Times',
  'jawaal': 'Jawaal',
  'prayerTimesTitle': 'Prayer Times',
  'hijriDateUnavailable': 'Hijri Date Unavailable',
  'nextPrefix': 'Next:',
  'prayerTimeSuffix': 'Prayer Time',
  'prayerFajr': 'Fajr',
  'prayerDhuhr': 'Dhuhr',
  'prayerAsr': 'Asr',
  'prayerMaghribAndIftar': 'Maghrib & Iftar',
  'prayerIsha': 'Isha',

  // Learning feature
  'learning': 'Learning',
  'explore': 'Explore',
  'exploreQuranicSciences': 'Quranic Sciences',
  'exploreDailyLife': 'Daily Life',
  'exploreIslamicHistory': 'Islamic History',
  'articlesCountLabel': 'Articles',
  'recentArticles': 'Recent Articles',
  'articleTitleSabr': 'The Power Of Sabr In Islam',
  'articleTagIslamicGuidance': 'Islamic Guidance',
  'articleExcerptSabr':
      'Learn how patience helps Muslims remain steadfast\nthrough difficulties and strengthens their trust in Allah.',
  'seeMore': 'See More . . .',
  'postDatePlaceholder': 'Post Date: August 17, 2026   10:00 AM',
  'allArticles': 'All Articles',
  'articlesDetails': 'Articles Details',
  'testLearning': 'Test Learning',
  'articleFullTextSabr':
      '''Sabr, or patience, is one of the most important virtues in Islam. It teaches believers to remain steadfast during hardships, control their emotions, and continue trusting in Allah's wisdom and plan. Life brings challenges, tests, and moments of uncertainty, but Sabr helps Muslims face these difficulties with faith, hope, and perseverance.

Patience does not mean giving up or simply waiting for problems to disappear. It means continuing to do what is right, maintaining faith during difficult moments, and seeking Allah's guidance when facing challenges. Through Sabr, a believer learns to respond to hardship with strength rather than despair.

The Quran reminds believers that Allah is with those who are patient. This gives Muslims comfort during difficult times and encourages them to remain hopeful.''',
  'questionProgressLabel': 'Question 12 of 20',
  'questionsTitlePlaceholder': 'Questions Title',
  'answerLabelPrefix': 'Answer',
  'quizTimingProgress': 'This Quiz Timing Progress',
  'previous': 'Previous',
  'next': 'Next',
  'timesRemainingLabel': 'Times Remaining : 07 : 03 Sec',
  'quizScore': 'Quiz Score',
  'testSubjectSabr': 'Sabr',
  'excellentWorkMessage':
      'Excellent Work! Your Answering Accuracy Is Very Good.\nKeep Up The Great Effort, And Continue Challenging\nYourself To Improve Even Further.',
  'timeSpent': 'Time Spent',
  'accuracy': 'Accuracy',
  'accuracyHigh': 'High',
  'whatsNext': 'Whats Next',
  'whatsNextMessage':
      'Would you like to move on to the next quiz? Click Next to\ncontinue, or choose Retry to retake the quiz and\nstrengthen your understanding.',
  'continueToNext': 'Continue To Next',
  'retryQuiz': 'Retry Quiz',
  'overallScore': 'Overall Score',
  'correctAnswers': 'Correct Answers',
  'incorrectAnswers': 'Incorrect Answers',
  'correctAnswersMessage':
      'You are trying your best your correct answer is 13 out of 20. Lets try to read learn more.',
  'incorrectAnswersMessage':
      'You are trying your best your correct answer is 7 out of 20. View incorrect answer and learn about it.',
  'viewCorrectAnswer': 'View Correct Answer',
  'viewIncorrectAnswer': 'View Incorrect Answer',

  // Planner feature
  'plannerPlanOne': 'Plan 1',
  'plannerPlanTwo': 'Plan 2',
  'createPlan': 'Create Plan',
  'myPlan': 'My Plan',
  'searchPlan': 'Search Plan',
  'completePlan': 'Complete Plan',
  'noCompletedPlansMessage': 'You cannot complete any\nplan yet !',
  'noPlansYetMessage': 'You don’t create any\nplan yet !',
  'planStatusComplete': 'Complete',
  'getStart': 'Get Start',
  'createPlanHeader': 'Create Plan',
  'planNameLabel': 'Plan Name',
  'planTargetDaysLabel': 'Target Days',
  'planTargetDaysHint': 'Eg : 30',
  'planEdit': 'Edit',
  'planDelete': 'Delete',
  'planComplete': 'Complete',
  'planEditTitle': 'Edit Plan',
  'planDeleteQuestion': 'Delete this plan?',
  'planCompleteQuestion': 'Mark this plan as complete?',
  'planCancel': 'Cancel',
  'writeHereHint': 'Write Here . . .',
  'selectQuizCategory': 'Select Quiz Category',
  'egQuranicScienceHint': 'Eg : Quranic science',
  'selectQuiz': 'Select Quiz',
  'egQuiz1Hint': 'Eg : Quiz 1',
  'add': 'Add',
  'create': 'Create',
  'addMore': 'Add More',
  'hadithCreatePlanTitle': 'Create plan',
  'selectHadithBook': 'Select Hadith book',
  'selectCategory': 'Select Category',
  'egSahihBukhariHint': 'Eg : Sahih Bukhari',
  'egHadithCategoryHint': 'Eg : Ohir Sucona',
  'hadithCategorySample': 'Ohir Sucona',
  'hadithCountSample': 'Hadith 7',

  // Quiz feature
  'categories': 'Categories',
  'quizzesCountLabel': 'Quizzes',
  'seerahAndHistory': 'Seerah & History',
  'islamicManners': 'Islamic Manners',
  'completeTodaysChallenge': 'Complete your todays\nchallenge',
  'letsGetStart': 'Lets Get Start',
  'highScore': 'High Score',
  'quizQuestionProgressLabel': 'Question 8 of 12',
  'fiftyFiftyChance': '50/50  CHANCE',
  'youCompletedTodaysChallenge': 'You completed your\ntodays challenge',
  'todaysPointsLabel': 'Todays points',
  'completedHistory': 'Completed History',
  'unableToLoadQuizHistory': 'Unable to load quiz history.',
  'tryAgain': 'Try Again',
  'learningNoCategories': 'No learning categories available.',
  'learningNoArticles': 'No articles found.',
  'learningNoSearchResults': 'No articles match your search.',
  'learningSearchArticles': 'Search articles . . .',
  'learningArticleNotFound': 'This article is no longer available.',
  'learningCategoryNotFound': 'This category could not be found.',
  'learningErrorInvalid':
      'The request could not be processed. Please try again.',
  'learningErrorRateLimit':
      'Too many requests. Please wait a moment and try again.',
  'learningNoContent': 'This article has no content yet.',
  'articlePublishedOn': 'Published: {date}',
  'articleByAuthor': 'By {author}',
  'quizQuestionOfTotal': 'Question {current} of {total}',
  'quizTimeRemaining': 'Times Remaining : {time}',
  'submit': 'Submit',
  'noQuizAvailable': 'No quiz available right now.',
  'unableToLoadQuiz': 'Unable to load the quiz.',
  'unableToLoadQuizCategories': 'Unable to load quiz categories.',
  'noQuizCategories': 'No quiz categories available right now.',
  'quizSubmitFailed':
      'Could not submit your answers. They are kept, please try again.',
  'dailyQuiz': 'Daily Quiz',
  'youCompletedTheQuiz': 'You Completed\nThe Quiz',
  'scoreLabel': 'Score',
  'reviewAnswers': 'Review Answers',
  'explanationLabel': 'Explanation',
  'notAnswered': 'Not answered',
  'noQuizAttemptsYet': "You haven't completed any quiz yet.",
  'bestScore': 'Best Score',
  'averageScore': 'Average Score',
  'attemptsLabel': 'Attempts',
  'unableToLoadAttempt': 'Unable to load this attempt.',
  'questionUnavailable': 'This question is no longer available.',
  'questionsWord': 'Questions',
  'allLabel': 'All',
  'noQuestionsInGroup': 'No questions here.',
  'planStatusPlanned': 'Planned',
  'planStatusInProgress': 'In Progress',
  'planStatusCompleted': 'Completed',
  'planStatusAbandoned': 'Abandoned',
  'startLabel': 'Start',
  'continueLabel': 'Continue',
  'abandonPlan': 'Abandon',
  'abandonPlanQuestion': 'Abandon this plan?',
  'abandonPlanNote': "It stays in your list, but can't be played any more.",
  'scheduleLabel': 'Schedule',
  'notScheduled': 'Not scheduled',
  'clearLabel': 'Clear',
  'notCompletedLabel': 'Not completed',
  'quizzesCompletedLabel': '{done} / {total} Quiz Completed',
  'percentCompleteLabel': '{percent}% Complete',
  'remainingLabel': 'Remaining',
  'numberOfQuizzes': 'Number of quizzes',
  'questionsPerQuiz': 'Questions per quiz',
  'planNameRequired': 'Enter a plan name.',
  'addAtLeastOneQuiz': 'Add at least one quiz.',
  'selectCategoryFirst': 'Select a category first.',
  'planCreated': 'Plan created',
  'planUpdated': 'Plan updated',
  'planAbandoned': 'Plan abandoned',
  'planSave': 'Save',
  'nextQuizLabel': 'Next Quiz',
  'backToPlan': 'Back to Plan',
  'planQuizLabel': 'Quiz {number}',
  'planErrorNotFound': 'This plan or quiz could not be found.',
  'planErrorAbandoned': 'This plan was abandoned.',
  'planErrorNotStarted': 'Start the plan first.',
  'planErrorPortionDone': 'This quiz is already completed.',
  'planErrorInvalid':
      'Please check the plan. A category may not have enough questions.',
  'noPlannedQuestions': 'No questions are available for this quiz.',
  'correctLabel': 'Correct',
  'incorrectLabel': 'Incorrect',
  'unansweredLabel': 'Unanswered',
  'answeredLabel': 'Answered',
  'correctPercentageLabel': 'Correct Rate',
  'totalTimeLabel': 'Total Time',
  'currentStreakLabel': 'Current Streak',
  'averageMinutesPerDayLabel': 'Avg. Min / Day',
  'completedAtLabel': 'Completed',
  'fiftyFiftyUsedLabel': '50/50 Used',
  'difficultyLabel': 'Difficulty',
  'quizCategoryLabel': 'Category',
  'minutesLabel': 'Minutes',
  'daysWord': 'days',
  'youLabel': 'You',
  'rankLabel': 'Rank',
  'aheadLabel': "You're ahead",
  'behindLabel': "You're behind",
  'noCompetitorYet': 'No one to compare with yet.',
  'quizComparisonTitle': 'Comparison',
  'dailyActivity': 'Daily Activity',
  'noQuizActivity': 'No quiz activity in this period.',
  'quizErrorNetwork': 'No internet connection. Please try again.',
  'quizErrorSession': 'Your session has expired. Please log in again.',
  'quizErrorForbidden': "You don't have access to this.",
  'quizErrorNotFound': 'This quiz attempt could not be found.',
  'quizErrorInvalidRange': 'The selected dates are not valid.',
  'quizErrorGeneric': 'Something went wrong. Please try again.',
  'learn': 'Learn',
  'planner': 'Planner',

  // Profile feature
  'profileTitle': 'Profile',
  'editProfileTitle': 'Edit Profile',
  'editProfileSelectPhotoTitle': 'Select Profile Photo',
  'editProfileChooseGallery': 'Choose from Gallery',
  'editProfileCancel': 'Cancel',
  'editProfileImagePickError':
      "Couldn't load the selected image. Please try again.",
  'editProfilePhotoUploadError': "Couldn't upload the photo. Please try again.",
  'percentCompleteSuffix': 'complete',
  'mymensingh': 'Mymensingh',
  'badgeLabel': 'Badge',
  'position': 'Position',
  'pointsWord': 'Points',
  'familyMember': 'Family Member',
  'brother': 'Brother',
  'familyMemberNameAbdullah': 'Abdullah',
  'familyMemberNameSabit': 'Sabit',
  'familyMemberNameAli': 'Ali',
  'logout': 'Logout',
  'logoutConfirmMessage': 'Are you sure you want to logout?',
  'yes': 'Yes',
  'no': 'No',
  'prayerNowLabel': 'Now',
  'loginRequiredMessage': 'You need to log in first to view this content.',

  // Settings feature
  'settingsTitle': 'Settings',
  'ebookOpenFailed': "Couldn't open this e-book",
  'hadithComplete': "Complete",
  'hadithCompleted': "Completed",
  'hadithCompletedQuestion':
      "Have you completed reading this Hadith? If you have completed it, points will be added to your account.",
  'hadithReadingTimeComplete': "Your reading time is complete. Please tap Yes.",
  'hadithGuestTrackQuestion': "Do you want to track this Hadith?",
  'hadithTrackFailed': "Couldn't save your reading progress. Please try again.",
  'folderNameInputHint': "Write folder name here.",
  'cancelAction': "Cancel",
  'ebookOpen': "Open book",
  'ebookDownloaded': "Saved on this device",
  'ebookDownloadFailed': "Download failed. Please try again.",
  'themeSwitchToDark': 'Switch to dark mode',
  'themeSwitchToLight': 'Switch to light mode',
  'aboutUs': 'About Us',
  'ourProducts': 'Our Products',
  'adminSupport': 'Admin Support',
  'feedback': 'Feedback',
  'appLanguage': 'App Language',
  'changePassword': 'Change Password',
  'deleteAccount': 'Delete Account',
  'deleteAccountConfirmPasswordTitle': 'Confirm Your Password',
  'deleteAccountConfirmPasswordMessage':
      'For your security, please enter your current password to continue with account deletion.',
  'deleteAccountPasswordHint': 'Enter your password',
  'deleteAccountEmptyPassword': 'Please enter your password.',
  'deleteAccountIncorrectPassword': 'Incorrect password. Please try again.',
  'deleteAccountFinalTitle': 'Delete Account?',
  'deleteAccountFinalMessage':
      'Are you sure you want to permanently delete your account? This action cannot be undone.',
  'deleteAccountFailureMessage':
      "We couldn't delete your account right now. Please try again.",

  // App language feature
  'languageTitle': 'Language',
  'bangla': 'Bangla',
  'english': 'English',
  'defaultLabel': 'Default',
  'allFamilyMembers': 'All Family Members',
  'familyMemberNameZulfikur': 'Zulfikur',
  'familyMemberNameAsif': 'Asif',

  // Quran feature
  'searchSurah': 'Search Surah',
  'surahsTitle': 'Surahs',
  'ayahWord': 'Ayahs',
  'surahMeaningOpening': 'The Opening',
  'surahMeaningCow': 'The Cow',
  'surahMeaningFamilyOfImran': 'The Family Of Imran',
  'surahMeaningWomen': 'The Women',
  'quranIntroSubtitle': 'Learn Quran And Recite Once Everyday',
  'quranLoadError': "Couldn't load the Quran. Please check your connection.",
  'hifjoQuranTitle': 'Hifjo Quran',
  'lastReadLabel': 'Last Read',
  'viewReadingHistory': 'View Reading History',
  'ayahNoLabel': 'Ayah No',
  'tabSurah': 'Surah',
  'tabPara': 'Para',
  'meccan': 'Meccan',
  'medinian': 'Medinian',
  'juzWord': 'Juz',
  'startsLabel': 'Starts',
  'bookmarksTitle': 'Bookmarks',
  'noBookmarksYet': 'No bookmarks yet',
  'readingHistoryTitle': 'Reading History',
  'noReadingHistoryYet': 'No reading history yet',
  'startReadingPrompt': 'Tap a surah below to begin',
  'viewFullSura': 'View Full Sura',
  'viewInAyat': 'View In Ayat',
  'pointsLabel': 'Points',
  'yourReadingTimeIs': 'Your Reading Time Is',
  'minLabel': 'min',
  'secLabel': 'sec',
  'viewQuranTafsir': 'View Quran Tafsir',
  'selectReciterTitle': 'Select Reciter',
  'tafsirTitle': 'Tafsir',
  'repeatLabel': 'Repeat',
  'showTransliterationLabel': 'Show Transliteration',
  'yearly': 'Yearly',
  'leaderboard': 'Leaderboard',
  'leaderboardTitle': 'Leader Board',
  'yourRank': 'Your Rank',
  'ptsToRank': 'Pts To Rank',
  'duaSettingsTitle': 'Dua Settings',
  'showArabicLabel': 'Show Arabic',
  'showTranslationLabel': 'Show Translation',
  // Shared validators, time, dates and client-side errors
  'validatorRequired': 'This field is required',
  'validatorEmailEmpty': 'Please enter your email',
  'validatorEmailInvalid': 'Please enter a valid email address',
  'validatorPasswordEmpty': 'Please enter your password',
  'validatorPasswordRule':
      'Use at least {min} characters with an uppercase letter, a number and a special character',
  'validatorPasswordMin': 'Password must be at least {min} characters',
  'validatorPasswordMax': 'Password must be at most {max} characters',
  'validatorNameEmpty': 'Please enter your name',
  'validatorNameShort': 'Please enter your full name',
  'validatorConfirmPasswordEmpty': 'Please confirm your password',
  'validatorPasswordMismatch': 'Passwords do not match',
  'validatorCurrentPasswordEmpty': 'Please enter your current password',
  'validatorNewPasswordEmpty': 'Please enter a new password',
  'validatorPasswordNoSpaces': 'Password cannot contain spaces',
  'validatorPasswordUppercase': 'Add at least one uppercase letter',
  'validatorPasswordLowercase': 'Add at least one lowercase letter',
  'validatorPasswordNumber': 'Add at least one number',
  'validatorPasswordSpecial': 'Add at least one special character',
  'validatorPasswordSameAsOld':
      'New password must be different from the current one',
  'validatorConfirmNewPasswordEmpty': 'Please confirm your new password',
  'validatorOtpCode': 'Enter the 6-digit code sent to your email',
  'validatorTermsRequired': 'Please accept the Terms of Service to continue',
  'passwordRequirementsHint':
      'Use {min}+ characters with uppercase, lowercase, a number and a special character.',
  'amLabel': 'AM',
  'pmLabel': 'PM',
  'hijriSuffix': 'Hijri',
  'failureNetwork': 'No internet connection. Please try again.',
  'failureTimeout': 'The request timed out. Please try again.',
  'failureSecureConnection': 'Could not establish a secure connection.',
  'failureCancelled': 'The request was cancelled.',
  'failureStorage': 'Failed to read local storage.',
  'failureUnknown': 'Something went wrong. Please try again.',
  'failureUnexpectedResponse':
      'Received an unexpected response from the server.',
  'failureRequestFailed': 'Request failed ({code}).',
  'failureNoSignedInUser': 'No signed in user found.',
  'failureNoPasswordSignIn': 'This account does not use password sign-in.',
  'failureMissingGoogleToken': 'Missing Google ID token.',
  // Auth, profile and legal screens
  'verificationCodeSent': 'A new code has been sent to your email.',
  'verificationResendFailed': 'Could not resend the code. Try again.',
  'verificationFailed': 'Verification failed. Please try again.',
  'resendCodeInSeconds': 'Resend code in {s}s',
  'didntGetCodeResend': 'Didn\'t get the code? Resend',
  'passwordUpdated': 'Your password has been updated.',
  'resetPasswordFailed': 'Could not reset password. Try again.',
  'signInFailed': 'Sign in failed. Please try again.',
  'registrationFailed': 'Registration failed. Please try again.',
  'currentPasswordHint': 'Current Password',
  'noDataHere': 'No data here',
  'legalEffectiveLabel': 'Effective: {date}',
  'legalLastUpdatedLabel': 'Last updated: {date}',
  // Hadith reading history time
  'readAtLabel': 'At',
  // Dua saved bookmarks and Amol confirmation
  'duaSavedEdit': 'Edit',
  'duaSavedDelete': 'Delete',
  'duaSavedTitle': 'Saved Hadith',
  'duaEditBookmarkTitle': 'Edit Book Mark',
  'duaFolderName': 'Folder name',
  'duaFolderNameHint': 'Write Folder Name Here.',
  'duaSaveChanges': 'Save Changes',
  'duaDeleteBookmarkTitle': 'Delete Book Mark',
  'duaDeleteBookmarkMessage':
      'Are you sure want to delete this\nbookmark right now?',
  'duaYesDelete': 'Yes, Delete',
  'duaSavedCount': '{n} Dua',
  'duaTotalSaved': 'Total Saved : {n}',
  'amolReadConfirmMessage':
      'Are you sure you have read this and want to track it?',
  'amolUntrackTitle': 'Untrack Amol?',
  'amolUntrackMessage': 'Are you sure you want to untrack "{name}"?',
  'leaderboardRankLabel': 'Rank',
  'leaderboardNotRanked': 'Not ranked in this period yet',
  'leaderboardFirstPlace': 'First place this period',
  'leaderboardPointsBehindFirst': '{points} points behind first place',
  'leaderboardPointsBehindFirstNamed': '{points} points behind {name}',
  'leaderboardParticipants': 'of {n} participants',
  'leaderboardTotalQuranTime': 'Total Quran Reading time',
  'leaderboardMostReadingSura': 'Most Reading Sura',
  // Quran screens
  'commonCancel': 'Cancel',
  'commonApply': 'Apply',
  'quranParaTitle': 'Para {n}',
  'quranNoSurahs': 'No surahs available',
  'quranParaRange': '{count} ayahs · {a}:{b} – {c}:{d}',
  'quranSurahAyahRange': '{name}\nAyah {from} – {to}',
  'quranAyahLoadFailed': 'Unable to load ayah. Please try again.',
  'quranPageLabel': 'Page {n}',
  'quranSurahChip': 'Surah:  {name}  ⌄',
  'quranFilterTitle': 'Filter Quran',
  'quranActions': 'Quran actions',
  'quranPageLoadFailedRetry': 'Could not load page. Retry',
  'quranNoAyahs': 'No ayahs available',
  'quranVerseInfo': '{key} · Para {para} · Page {page}',
  'quranTafsirVerse': 'Tafsir · {key}',
  'quranCloseTafsir': 'Close tafsir',
  'quranSurahPage': 'Surah: {name} · Page {page}',
  'quranTajweedDownload': 'Tajweed / Download Quran',
  'quranSearchSurahOrPara': 'Search Surah Or Para',
  'quranNoResults': 'No results',
  'quranBrowseHint':
      'Browse by Surah or Para. Page numbers are shown while reading; page browsing is coming soon.',
  'quranTranslateHeading': 'Translate',
  'quranSelectTranslateLanguage': 'Select translate language',
  'quranRetryLanguages': 'Retry languages',
  'quranNoTranslations': 'No translations available',
  'quranCopy': 'Copy',
  'quranShare': 'Share',
  'quranPlayAyah': 'Play ayah',
  'quranBookmarkAyah': 'Bookmark ayah',
  'quranSajdah': 'Sajdah {n}',
  'quranTajweedTitle': 'Tajweed Quran',
  'quranTajweedUnavailable':
      'A Tajweed edition is not available from the current Quran API. You can download the standard Quran for offline reading below.',
  'quranDownloadInterrupted': 'Download interrupted. Retry to continue.',
  'quranKeepScreenOpen': 'Keep this screen open until the download completes.',
  'quranNoFilters': 'No Quran filters available',
  'quranJuzParaCarousel': 'Juz / Para Carousel',
  'quranSearchAndSelectSurah': 'Search and Select Surah',
  'quranSelectedSurah': 'Selected: {n}. {name}',
  'quranNoSurahsFound': 'No Surahs found',
  'quranSurahTranslationAyahs': '{translation} · {n} ayahs',
  'quranSelectAyat': 'Select Ayat',
  'quranAyahNumber': 'Ayah {n}',
  'quranAyahCopied': 'Ayah copied',
  'quranShareFailed': 'Unable to share this ayah. Please try again.',
  'quranSurahAyahCount': '{n} · {total} ayahs',
  'quranSurahHeadingInfo': '{place} • {n} AYAT',
  'quranBismillah': 'Bismillah',
  'quranAyahTitle': 'Quran {key}',
  'quranAudioAyahTitle': 'Ayah {key}',
  // Quran screens (2)
  'quranRangeEnd': 'end',
  // More failure messages and Quran/Hadith labels
  'failurePasswordRule':
      'Password must be at least {min} characters and include an uppercase letter, a number and a special character.',
  'failureResetSessionExpired':
      'Your reset session has expired. Please request a new code.',
  'failureGoogleUnavailable': 'Google Sign-In is unavailable on this platform.',
  'failureAudioServer':
      'Could not reach the audio server. Check your connection.',
  'failureNoAudioSurah': 'No audio available for this surah.',
  'failureNoAudioAyah': 'No audio available for this ayah.',
  'failureAudioDownload': 'Audio download failed ({key}).',
  'failureQuranContent': 'Unable to load Quran content.',
  'failureDownloadInterrupted':
      'Download interrupted at surah {n}. Check your connection and resume.',
  'failureSurahListLoad': 'Could not load the surah list.',
  'failureNotAvailableOffline': 'This is not available offline.',
  'failureContentLoad': 'Could not load this content. Please try again.',
  'failureTranslationBuiltIn': 'This translation is already built in.',
  'failureNoTranslationSurah': 'No translation available for surah {n}.',
  'failureEbookNoPdf': 'The e-book has no PDF file.',
  'failureDownloadFailed': 'Download failed.',
  'quranSurahBookmarked': 'Surah bookmarked',
  'quranSurahBookmarkRemoved': 'Surah bookmark removed',
  'quranViewInAyat': 'View in ayat',
  'quranChangeText': 'Change text',
  'quranTranslationUnavailable': 'Translation unavailable for this ayah',
  'quranReadyOffline': 'Quran ready for offline reading',
  'quranDownloading': 'Downloading Quran',
  'commonDone': 'Done',
  'quranRetryDownload': 'Retry download',
  'quranDownloadQuran': 'Download Quran',
  'quranShareTranslation': 'Translation: {name}',
  'quranNoTafsir': 'No Tafsir available for this ayah',
  'hadithTimeMinutes': 'Time : {n} min',
  'hadithPointValue': 'Point : {n}',
  // Hadith dashboard chart
  'hadithCompetitor': 'Competitor',
  // Quran menu and offline
  'quranBookmarkSurah': 'Book Mark Surah',
  'quranOfflineTitle': 'Offline Quran',
  // Remaining labels found by the audit
  'quranSurahNumberTitle': 'Surah {n}',
  'hadithTimerRead': 'Read',
  'hadithTimerReading': 'Reading…',
  'hadithTimerPaused': 'Paused',
  'calendarArabicInBangla': 'Arabic calendar in Bangla',
  // Quran filter chips
  'quranAllTypes': 'All Types',
  'failureQuranPlanDuplicateName':
      'You already have a Quran plan with this name.',
  'failureQuranPlanLoad': 'Failed to load Quran plans.',
  'failureQuranPlanCreate': 'Failed to create Quran plan.',
  'failureQuranPlanUpdate': 'Failed to update Quran plan.',
  'failureQuranPlanDetailsLoad': 'Failed to load plan details.',
  'failureQuranPlanAyahsLoad': 'Failed to load plan Ayahs.',
  'failureQuranPlanComplete': 'Failed to complete plan.',
  'failureQuranPlanDelete': 'Failed to delete plan.',
  'failureQuranPlanNotFound': 'Plan not found.',
  'failureQuranPlanUnreadAyahs':
      'You still have {count} Ayahs left to read before completing this plan.',
  'failureQuranPlaylistDuplicateName':
      'You already have a Quran playlist with this name.',
  'failureQuranPlaylistLoad': 'Failed to load Quran playlists.',
  'failureQuranPlaylistCreate': 'Failed to create Quran playlist.',
  'failureQuranPlaylistUpdate': 'Failed to update Quran playlist.',
  'failureQuranPlaylistDetailsLoad': 'Failed to load playlist details.',
  'failureQuranPlaylistAyahsLoad': 'Failed to load playlist Ayahs.',
  'failureQuranPlaylistDelete': 'Failed to delete playlist.',
  'failureQuranPlaylistNotFound': 'Playlist not found.',
};
