const Map<String, String> appTextBn = <String, String>{
  'noorify': 'নূরিফাই ডেমো লোগো',
  'splashTitle': 'বিশ্বাসে খুঁজে নিন শান্তি',
  'splashQuote':
      'কুরআন তিলাওয়াত, দোয়া এবং সময়মতো নামাজের স্মরণ দিয়ে অর্থবহ দৈনন্দিন অভ্যাস গড়ে তুলুন।',
  'emailOrPhoneHint': 'ইমেইল অথবা ফোন নম্বর',
  'passwordHint': 'পাসওয়ার্ড',
  'forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন',
  'login': 'লগইন',
  'newToNoorify': 'নূরিফাইতে নতুন?',
  'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
  'signUpSubtitle': 'আরও মননশীল ইসলামিক জীবনযাত্রার পথচলা শুরু করুন।',
  'enterYourName': 'আপনার নাম দিন',
  'emailAddress': 'ইমেইল',
  'emailVerification': 'ইমেইল যাচাই',
  'sendOtp': 'ওটিপি পাঠান',
  'otpVerification': 'ওটিপি যাচাই',
  'verify': 'যাচাই করুন',
  'resendIn': 'পুনরায় পাঠান  ০১: ২৩ সেকেন্ড',
  'resetPassword': 'পাসওয়ার্ড রিসেট',
  'newPassword': 'নতুন পাসওয়ার্ড',
  'confirm': 'নিশ্চিত করুন',
  'phoneNo': 'ফোন নম্বর',
  'gender': 'লিঙ্গ',
  'male': 'পুরুষ',
  'female': 'নারী',
  'confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
  'signUpWithOthers': 'অন্যান্য মাধ্যমে সাইন আপ',
  'togglePassword': 'পাসওয়ার্ড দেখুন',
  'iAgreeToThe': 'আমি',
  'termsOfServices': 'সেবার শর্তাবলী',
  'privacyPolicy': 'গোপনীয়তা নীতি',
  'alreadyHaveAccount': 'আগে থেকেই অ্যাকাউন্ট আছে?',
  'logIn': 'লগ ইন',

  // Shared
  'back': 'পিছনে',

  // Alarm feature
  'setAlarm': 'অ্যালার্ম সেট করুন',
  'setAllAlarm': 'সব অ্যালার্ম সেট করুন',
  'vibrateAndRing': 'কম্পন ও রিং',
  'setRingtone': 'রিংটোন সেট করুন',
  'vibrate': 'কম্পন',
  'ring': 'রিং',
  'searchHere': 'এখানে খুঁজুন . . .',
  'setAlarmBeforePrayer': 'নামাজের আগে অ্যালার্ম সেট করুন',
  'setAlarmFor': 'এর জন্য অ্যালার্ম সেট করুন',
  'offsetAtPrayerTime': 'নামাজের সময়ে',
  'offsetBefore5Min': '৫ মিনিট আগে',
  'offsetBefore10Min': '১০ মিনিট আগে',
  'offsetBefore15Min': '১৫ মিনিট আগে',
  'offsetBefore20Min': '২০ মিনিট আগে',
  'offsetBefore30Min': '৩০ মিনিট আগে',
  'offsetBefore40Min': '৪০ মিনিট আগে',
  'offsetBefore60Min': '৬০ মিনিট আগে',

  // Amol tracking feature
  'amolTracking': 'আমল ট্র্যাকিং',
  'daily': 'দৈনিক',
  'weekly': 'সাপ্তাহিক',
  'monthly': 'মাসিক',
  'point': 'পয়েন্ট',
  'myPoints': 'আমার পয়েন্ট',
  'todaysAmolTrack': 'আজকের আমল ট্র্যাক',
  'amolTrack': 'আমল ট্র্যাক',
  'todays': 'আজকের',
  'averageTodaysDays': '– আজকের দিনের গড়।',
  'myPosition': 'আমার অবস্থান',
  'myNearestOrCompetitor': 'আমার নিকটতম বা প্রতিযোগী',
  'competitorInitials': 'আঃ',
  'viewInDashboard': 'ড্যাশবোর্ডে দেখুন',
  'categoryFardhPrayer': 'ফরজ নামাজ',
  'categorySunnahAndWitr': 'সুন্নত ও বিতর',
  'categoryQuran': 'কুরআন',
  'categoryNaflSalat': 'নফল সালাত',
  'categoryHadith': 'হাদিস',
  'hadithIntroTitle': 'হাদিস ও বই',
  'hadithIntroSubtitle':
      'দৈনন্দিন শিক্ষা, অনুধাবন ও আত্মিক উন্নতির জন্য নির্ভরযোগ্য ইসলামিক উৎস থেকে যাচাইকৃত হাদিস পড়ুন।',
  'hadithIntroStartButton': 'শুরু করুন',
  'hadithTotalHadith': 'মোট হাদিস',
  'hadithLastRead': 'সর্বশেষ পঠিত',
  'hadithLibrary': 'হাদিস লাইব্রেরি',
  'hadithEbook': 'ই-বুক',
  'hadithLibraryTitle': 'হাদিস লাইব্রেরি',
  'hadithCategory': 'হাদিস ক্যাটাগরি',
  'hadithBookDownloadTitle': 'অফলাইনে পড়তে ডাউনলোড করুন',
  'hadithBookDownloadBody':
      'বইটি একবার আপনার ডিভাইসে সংরক্ষণ হবে, এরপর ইন্টারনেট ছাড়াই সঙ্গে সঙ্গে খুলবে।',
  'hadithBookDownloadAction': 'বই ডাউনলোড করুন',
  'hadithBookDownloading': 'বই ডাউনলোড হচ্ছে',
  'hadithBookComingSoon': 'শীঘ্রই আসছে',
  'hadithBookReference': 'তথ্যসূত্র',
  'hadithSwipeNext': 'পরবর্তী হাদিসের জন্য সোয়াইপ করুন',
  'hadithCopy': 'হাদিস কপি করুন',
  'hadithCopied': 'হাদিস কপি হয়েছে',
  'categoryQuiz': 'কুইজ',
  'categoryNaflAndMore': 'নফল ও আরও',
  'salahFajr': 'ফজর',
  'salahDuhr': 'যোহর',
  'salahAsr': 'আসর',
  'salahMagrib': 'মাগরিব',
  'salahEsa': 'এশা',
  'salahFajrSunnah': 'ফজরের সুন্নত',
  'salahDuhrSunnah': 'যোহরের সুন্নত',
  'salahAsrSunnah': 'আসরের সুন্নত',
  'salahMagribSunnah': 'মাগরিবের সুন্নত',
  'salahEsaSunnah': 'এশার সুন্নত',
  'salahWitr': 'বিতর',
  'naflTahajjud': 'তাহাজ্জুদ',
  'naflIshraq': 'ইশরাক',
  'naflChast': 'চাশত',
  'naflAwabin': 'আওয়াবিন',
  'moreSadaqah': 'সদকা',
  'moreKarzeHasanah': 'করজে হাসানা',
  'moreNaflFasting': 'নফল রোজা',
  'morePhysicalExercise': 'শরীরচর্চা',
  'moreGivenGoodAdvice': 'উত্তম উপদেশ দেওয়া',
  'moreSkillDevelopment': 'দক্ষতা উন্নয়ন',
  'infoQuranTilawat': 'কুরআন তিলাওয়াত',
  'infoHadithReading': 'হাদিস অধ্যয়ন',
  'infoGivingQuiz': 'কুইজ দেওয়া',
  'weekdayMonday': 'সোমবার',
  'weekdayTuesday': 'মঙ্গলবার',
  'weekdayWednesday': 'বুধবার',
  'weekdayThursday': 'বৃহস্পতিবার',
  'weekdayFriday': 'শুক্রবার',
  'weekdaySaturday': 'শনিবার',
  'weekdaySunday': 'রবিবার',
  'monthJanuary': 'জানুয়ারি',
  'monthFebruary': 'ফেব্রুয়ারি',
  'monthMarch': 'মার্চ',
  'monthApril': 'এপ্রিল',
  'monthMay': 'মে',
  'monthJune': 'জুন',
  'monthJuly': 'জুলাই',
  'monthAugust': 'আগস্ট',
  'monthSeptember': 'সেপ্টেম্বর',
  'monthOctober': 'অক্টোবর',
  'monthNovember': 'নভেম্বর',
  'monthDecember': 'ডিসেম্বর',

  // Shared social labels
  'google': 'গুগল',
  'facebook': 'ফেসবুক',

  // Auth error messages
  'authErrorInvalidEmail': 'একটি বৈধ ইমেইল ঠিকানা দিন।',
  'authErrorUserDisabled': 'এই অ্যাকাউন্টটি নিষ্ক্রিয় করা হয়েছে।',
  'authErrorWrongCredentials': 'ইমেইল অথবা পাসওয়ার্ড সঠিক নয়।',
  'authErrorAccountNotPasswordBased':
      'এই অ্যাকাউন্টটি গুগল সাইন-ইন ব্যবহার করে। পাসওয়ার্ড পরিবর্তন করা যাবে না।',
  'authErrorEmailInUse': 'এই ইমেইলটি ইতিমধ্যে ব্যবহৃত হয়েছে। লগইন করুন।',
  'authErrorWeakPassword':
      'পাসওয়ার্ডটি খুবই দুর্বল। কমপক্ষে ৬টি অক্ষর ব্যবহার করুন।',
  'authErrorOperationNotAllowed':
      'এই সাইন-ইন পদ্ধতিটি ফায়ারবেসে সক্রিয় নেই।',
  'authErrorRequiresRecentLogin':
      'পাসওয়ার্ড পরিবর্তনের আগে আবার লগইন করুন।',
  'authErrorAccountExistsDifferentCredential':
      'ভিন্ন সাইন-ইন পদ্ধতিতে ইতিমধ্যে একটি অ্যাকাউন্ট আছে।',
  'authErrorCredentialAlreadyInUse':
      'এই গুগল অ্যাকাউন্টটি ইতিমধ্যে অন্য ব্যবহারকারীর সাথে যুক্ত।',
  'authErrorTooManyRequests': 'অনেকবার চেষ্টা করা হয়েছে। পরে আবার চেষ্টা করুন।',
  'authErrorNetworkFailed':
      'নেটওয়ার্ক ত্রুটি। আপনার ইন্টারনেট সংযোগ পরীক্ষা করুন।',
  'authErrorGeneric': 'প্রমাণীকরণ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
  'googleAuthErrorNotConfigured': 'গুগল সাইন-ইন এখনও সঠিকভাবে কনফিগার করা হয়নি।',
  'googleAuthErrorUiUnavailable':
      'এই ডিভাইসে গুগল সাইন-ইন বর্তমানে ব্যবহারযোগ্য নয়।',
  'googleAuthErrorInterrupted': 'গুগল সাইন-ইন বাধাগ্রস্ত হয়েছে। আবার চেষ্টা করুন।',
  'googleAuthErrorGeneric': 'গুগল সাইন-ইন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',

  // Dashboard feature
  'dashboard': 'ড্যাশবোর্ড',
  'quizHistory': 'কুইজের ইতিহাস',
  'seeAll': 'সব দেখুন',
  'averageValue': 'গড় মান',
  'dailyQuizValue': 'দৈনিক কুইজ মান',
  'weeklyQuizValue': 'সাপ্তাহিক কুইজ মান',
  'monthlyQuizValue': 'মাসিক কুইজ মান',
  'competitorName': 'আব্দুল্লাহ আল-আজিজ',
  'quranicScience': 'কুরআনিক বিজ্ঞান',
  'questionsCountLabel': '২০টি প্রশ্ন',

  // Home feature
  'greeting': 'আসসালামু আলাইকুম ওয়া রাহমাতুল্লাহ',
  'timer': 'টাইমার',
  'notifications': 'নোটিফিকেশন',
  'featureDua': 'দোয়া',
  'featureDijpr': 'যিকর',
  'featureAsmaUlHusna': 'আসমাউল হুসনা',
  'featureQuizAndLearn': 'কুইজ ও শিখুন',
  'zakatCalculator': 'যাকাত ক্যালকুলেটর',
  'ageCalculate': 'বয়স গণনা',
  'home': 'হোম',
  'todaysHighestValue': 'আজকের সর্বোচ্চ মান',
  'todays2ndHighest': 'আজকের ২য় সর্বোচ্চ',
  'yesterdaysHighest': 'গতকালের সর্বোচ্চ',
  'khalidSaifullah': 'খালিদ সাইফুল্লাহ',
  'myPositionInMonth': 'জুলাই মাসে আমার অবস্থান',
  'firstInTheMonth': 'মাসে ১ম',
  'secondInTheMonth': 'মাসে ২য়',
  'lastMonthWinner': 'গত মাসের বিজয়ী',
  'sehri': 'সেহরি',
  'iftar': 'ইফতার',
  'hijriDatePlaceholder': '৭ সফর ১৪৪৪ হিজরি',
  'bengaliDatePlaceholder': '৭ শ্রাবণ ১৪৩৩',
  'gregorianDatePlaceholder': '২৪ জুলাই ২০২৬',
  'locationPlaceholder': 'ময়মনসিংহ, বাংলাদেশ',
  'viewPrayerTimes': 'নামাজের সময় দেখুন',
  'sunrise': 'সূর্যোদয়',
  'sunset': 'সূর্যাস্ত',
  'trishal': 'ত্রিশাল',
  'sunriseTimePlaceholder': 'ভোর ৫:২৩',
  'sunsetTimePlaceholder': 'সন্ধ্যা ৬:৫৪',
  'dhuhrPrayerTime': 'যোহরের নামাজের সময়',
  'prohibitedPrayerTimes': 'নিষিদ্ধ নামাজের সময়',
  'jawaal': 'জাওয়াল',
  'prayerTimesTitle': 'নামাজের সময়',
  'hijriDateUnavailable': 'হিজরি তারিখ পাওয়া যায়নি',
  'nextPrefix': 'পরবর্তী:',
  'prayerTimeSuffix': 'নামাজের সময়',
  'prayerFajr': 'ফজর',
  'prayerDhuhr': 'যোহর',
  'prayerAsr': 'আসর',
  'prayerMaghribAndIftar': 'মাগরিব ও ইফতার',
  'prayerIsha': 'এশা',

  // Learning feature
  'learning': 'শিক্ষা',
  'explore': 'অন্বেষণ',
  'exploreQuranicSciences': 'কুরআনিক বিজ্ঞান',
  'exploreDailyLife': 'দৈনন্দিন জীবন',
  'exploreIslamicHistory': 'ইসলামিক ইতিহাস',
  'articlesCountLabel': 'প্রবন্ধ',
  'recentArticles': 'সাম্প্রতিক প্রবন্ধ',
  'articleTitleSabr': 'ইসলামে ধৈর্যের শক্তি',
  'articleTagIslamicGuidance': 'ইসলামিক নির্দেশনা',
  'articleExcerptSabr':
      'জেনে নিন কীভাবে ধৈর্য মুসলিমদের কঠিন পরিস্থিতিতে অবিচল থাকতে সাহায্য করে\nএবং আল্লাহর প্রতি তাদের বিশ্বাসকে দৃঢ় করে।',
  'seeMore': 'আরও দেখুন . . .',
  'postDatePlaceholder': 'প্রকাশের তারিখ: ১৭ আগস্ট, ২০২৬   সকাল ১০:০০',
  'allArticles': 'সব প্রবন্ধ',
  'articlesDetails': 'প্রবন্ধের বিস্তারিত',
  'testLearning': 'শেখা যাচাই করুন',
  'articleFullTextSabr':
      '''সবর বা ধৈর্য ইসলামের অন্যতম গুরুত্বপূর্ণ একটি গুণ। এটি বিশ্বাসীদের কষ্টের সময় অবিচল থাকতে, তাদের আবেগ নিয়ন্ত্রণ করতে এবং আল্লাহর প্রজ্ঞা ও পরিকল্পনার প্রতি বিশ্বাস অব্যাহত রাখতে শেখায়। জীবনে চ্যালেঞ্জ, পরীক্ষা এবং অনিশ্চয়তার মুহূর্ত আসে, কিন্তু সবর মুসলিমদের এই কঠিনতাগুলো বিশ্বাস, আশা এবং অধ্যবসায়ের সাথে মোকাবিলা করতে সাহায্য করে।

ধৈর্য মানে হাল ছেড়ে দেওয়া বা শুধু সমস্যা মিলিয়ে যাওয়ার অপেক্ষা করা নয়। এর অর্থ হলো সঠিক কাজ চালিয়ে যাওয়া, কঠিন মুহূর্তে বিশ্বাস বজায় রাখা এবং চ্যালেঞ্জের মুখে আল্লাহর নির্দেশনা খোঁজা। সবরের মাধ্যমে একজন বিশ্বাসী হতাশার পরিবর্তে শক্তি দিয়ে কষ্টের জবাব দিতে শেখেন।

কুরআন বিশ্বাসীদের স্মরণ করিয়ে দেয় যে আল্লাহ ধৈর্যশীলদের সাথে আছেন। এটি মুসলিমদের কঠিন সময়ে সান্ত্বনা দেয় এবং তাদের আশাবাদী থাকতে উৎসাহিত করে।''',
  'questionProgressLabel': '২০টির মধ্যে ১২তম প্রশ্ন',
  'questionsTitlePlaceholder': 'প্রশ্নের শিরোনাম',
  'answerLabelPrefix': 'উত্তর',
  'quizTimingProgress': 'এই কুইজের সময় অগ্রগতি',
  'previous': 'পূর্ববর্তী',
  'next': 'পরবর্তী',
  'timesRemainingLabel': 'অবশিষ্ট সময় : ০৭ : ০৩ সেকেন্ড',
  'quizScore': 'কুইজ স্কোর',
  'testSubjectSabr': 'সবর',
  'excellentWorkMessage':
      'চমৎকার কাজ! আপনার উত্তরের নির্ভুলতা খুবই ভালো।\nএই প্রচেষ্টা অব্যাহত রাখুন এবং নিজেকে আরও উন্নত\nকরতে চ্যালেঞ্জ করতে থাকুন।',
  'timeSpent': 'ব্যয়িত সময়',
  'accuracy': 'নির্ভুলতা',
  'accuracyHigh': 'উচ্চ',
  'whatsNext': 'এরপর কী',
  'whatsNextMessage':
      'আপনি কি পরবর্তী কুইজে যেতে চান? চালিয়ে যেতে Next চাপুন,\nঅথবা কুইজটি আবার দিতে এবং আপনার বোঝাপড়া\nদৃঢ় করতে Retry বেছে নিন।',
  'continueToNext': 'পরবর্তীতে যান',
  'retryQuiz': 'আবার চেষ্টা করুন',
  'overallScore': 'সামগ্রিক স্কোর',
  'correctAnswers': 'সঠিক উত্তর',
  'incorrectAnswers': 'ভুল উত্তর',
  'correctAnswersMessage':
      'আপনি যথাসাধ্য চেষ্টা করছেন, আপনার সঠিক উত্তর ২০টির মধ্যে ১৩টি। আরও শিখতে পড়ার চেষ্টা করুন।',
  'incorrectAnswersMessage':
      'আপনি যথাসাধ্য চেষ্টা করছেন, আপনার সঠিক উত্তর ২০টির মধ্যে ৭টি। ভুল উত্তরগুলো দেখুন এবং সে সম্পর্কে জানুন।',
  'viewCorrectAnswer': 'সঠিক উত্তর দেখুন',
  'viewIncorrectAnswer': 'ভুল উত্তর দেখুন',

  // Planner feature
  'plannerPlanOne': 'পরিকল্পনা ১',
  'plannerPlanTwo': 'পরিকল্পনা ২',
  'createPlan': 'পরিকল্পনা তৈরি করুন',
  'myPlan': 'আমার পরিকল্পনা',
  'completePlan': 'সম্পূর্ণ পরিকল্পনা',
  'noCompletedPlansMessage': 'আপনি এখনও কোনো\nপরিকল্পনা সম্পূর্ণ করতে পারেননি!',
  'getStart': 'শুরু করুন',
  'createPlanHeader': 'পরিকল্পনা তৈরি করুন',
  'planNameLabel': 'পরিকল্পনার নাম',
  'writeHereHint': 'এখানে লিখুন . . .',
  'selectQuizCategory': 'কুইজ বিভাগ নির্বাচন করুন',
  'egQuranicScienceHint': 'যেমন : কুরআনিক বিজ্ঞান',
  'selectQuiz': 'কুইজ নির্বাচন করুন',
  'egQuiz1Hint': 'যেমন : কুইজ ১',
  'add': 'যোগ করুন',
  'create': 'তৈরি করুন',
  'addMore': 'আরও যোগ করুন',

  // Quiz feature
  'categories': 'বিভাগসমূহ',
  'quizzesCountLabel': 'কুইজ',
  'seerahAndHistory': 'সিরাত ও ইতিহাস',
  'islamicManners': 'ইসলামিক শিষ্টাচার',
  'completeTodaysChallenge': 'আপনার আজকের\nচ্যালেঞ্জ সম্পূর্ণ করুন',
  'letsGetStart': 'চলুন শুরু করি',
  'highScore': 'সর্বোচ্চ স্কোর',
  'quizQuestionProgressLabel': '১২টির মধ্যে ৮ম প্রশ্ন',
  'fiftyFiftyChance': '৫০/৫০  সুযোগ',
  'youCompletedTodaysChallenge': 'আপনি আপনার আজকের\nচ্যালেঞ্জ সম্পূর্ণ করেছেন',
  'todaysPointsLabel': 'আজকের পয়েন্ট',
  'completedHistory': 'সম্পন্ন ইতিহাস',
  'unableToLoadQuizHistory': 'কুইজের ইতিহাস লোড করা যায়নি।',
  'tryAgain': 'আবার চেষ্টা করুন',
  'questionsWord': 'প্রশ্ন',
  'learn': 'শিখুন',
  'planner': 'পরিকল্পনাকারী',

  // Profile feature
  'profileTitle': 'প্রোফাইল',
  'percentCompleteSuffix': 'সম্পন্ন',
  'mymensingh': 'ময়মনসিংহ',
  'badgeLabel': 'ব্যাজ',
  'position': 'অবস্থান',
  'pointsWord': 'পয়েন্ট',
  'familyMember': 'পরিবারের সদস্য',
  'brother': 'ভাই',
  'familyMemberNameAbdullah': 'আব্দুল্লাহ',
  'familyMemberNameSabit': 'সাবিত',
  'familyMemberNameAli': 'আলী',
  'logout': 'লগআউট',

  // Settings feature
  'settingsTitle': 'সেটিংস',
  'aboutUs': 'আমাদের সম্পর্কে',
  'ourProducts': 'আমাদের পণ্য',
  'adminSupport': 'অ্যাডমিন সাপোর্ট',
  'feedback': 'মতামত',
  'appLanguage': 'অ্যাপের ভাষা',
  'changePassword': 'পাসওয়ার্ড পরিবর্তন করুন',
  'deleteAccount': 'অ্যাকাউন্ট মুছুন',

  // App language feature
  'languageTitle': 'ভাষা',
  'bangla': 'বাংলা',
  'english': 'ইংরেজি',
  'defaultLabel': 'ডিফল্ট',
  'allFamilyMembers': 'সকল পরিবারের সদস্য',
  'familyMemberNameZulfikur': 'জুলফিকার',
  'familyMemberNameAsif': 'আসিফ',

  // Quran feature
  'searchSurah': 'সূরা খুঁজুন',
  'surahsTitle': 'সূরাসমূহ',
  'ayahWord': 'আয়াত',
  'surahMeaningOpening': 'সূচনা',
  'surahMeaningCow': 'গাভী',
  'surahMeaningFamilyOfImran': 'ইমরান পরিবার',
  'surahMeaningWomen': 'নারী',
  'quranIntroSubtitle': 'কুরআন শিখুন এবং প্রতিদিন তিলাওয়াত করুন',
  'quranLoadError': 'কুরআন লোড করা যায়নি। আপনার সংযোগ পরীক্ষা করুন।',
  'hifjoQuranTitle': 'হিফজো কুরআন',
  'lastReadLabel': 'সর্বশেষ পঠিত',
  'viewReadingHistory': 'পঠন ইতিহাস দেখুন',
  'ayahNoLabel': 'আয়াত নং',
  'tabSurah': 'সূরা',
  'tabPara': 'পারা',
  'meccan': 'মক্কী',
  'medinian': 'মাদানী',
  'juzWord': 'পারা',
  'startsLabel': 'শুরু',
  'bookmarksTitle': 'বুকমার্ক',
  'noBookmarksYet': 'এখনো কোনো বুকমার্ক নেই',
  'readingHistoryTitle': 'পঠন ইতিহাস',
  'noReadingHistoryYet': 'এখনো কোনো পঠন ইতিহাস নেই',
  'startReadingPrompt': 'শুরু করতে নিচের একটি সূরা নির্বাচন করুন',
  'viewFullSura': 'সম্পূর্ণ সূরা দেখুন',
  'viewInAyat': 'আয়াত আকারে দেখুন',
  'pointsLabel': 'পয়েন্ট',
  'yourReadingTimeIs': 'আপনার পঠন সময়',
  'minLabel': 'মিনিট',
  'secLabel': 'সেকেন্ড',
  'viewQuranTafsir': 'কুরআন তাফসীর দেখুন',
  'selectReciterTitle': 'ক্বারী নির্বাচন করুন',
  'tafsirTitle': 'তাফসীর',
  'repeatLabel': 'পুনরাবৃত্তি',
};
